apiVersion: v1
kind: Pod
metadata:
  name: filesyncer
spec:
  containers:
  - name: filesyncer
    image: onepanel/filesyncer:v0.18.0
    args:
      - server
      # This exposes filsyncer sync endpoint at /sys/filesyncer/api/sync
      - -server-prefix=/sys/filesyncer
    volumeMounts:
    - name: sys-namespace-config
      mountPath: /etc/onepanel
      readOnly: true
    - name: data
      mountPath: /mnt/data
  volumes:
  - name: data
    emptyDir: {}
  # Note that this is automatically injected in Onepanel
  - name: sys-namespace-config
    projected:
      sources:
        - secret:
            name: onepanel
        - configMap:
            name: onepanel
