# Can be added to:
#   - `postExecutionWorkflow` in Workspaces
#   - As a Task and template to Workflows
entrypoint: main
templates:
- name: main
  dag:
     tasks:
      - name: slack-notify
        template: slack-notify
- name: slack-notify
  container:
    image: technosophos/slack-notify
    env:
     - name: SLACK_USERNAME
       value: onepanel
     - name: SLACK_ICON
       value: https://www.gravatar.com/avatar/5c4478592fe00878f62f0027be59c1bd
    command:
     - sh
     - -c
    args:
     - SLACK_TITLE="Workspace {{workspace.name}} status"
     - SLACK_MESSAGE="Workspace {{workspace.name}} status has changed"
     - ./slack-notify